export const STATE_TERRITORY_AREA_OPTIONS = [
  { code: 'AL', label: 'Alabama' },
  { code: 'AK', label: 'Alaska' },
  { code: 'AS', label: 'American Samoa' },
  { code: 'AR', label: 'Arkansas' },
  { code: 'AZ', label: 'Arizona' },
  { code: 'CA', label: 'California' },
  { code: 'CO', label: 'Colorado' },
  { code: 'CT', label: 'Connecticut' },
  { code: 'DE', label: 'Delaware' },
  { code: 'DC', label: 'District of Columbia' },
  { code: 'FL', label: 'Florida' },
  { code: 'GA', label: 'Georgia' },
  { code: 'GU', label: 'Guam' },
  { code: 'HI', label: 'Hawaii' },
  { code: 'ID', label: 'Idaho' },
  { code: 'IL', label: 'Illinois' },
  { code: 'IN', label: 'Indiana' },
  { code: 'IA', label: 'Iowa' },
  { code: 'KS', label: 'Kansas' },
  { code: 'KY', label: 'Kentucky' },
  { code: 'LA', label: 'Louisiana' },
  { code: 'ME', label: 'Maine' },
  { code: 'MD', label: 'Maryland' },
  { code: 'MA', label: 'Massachusetts' },
  { code: 'MI', label: 'Michigan' },
  { code: 'MN', label: 'Minnesota' },
  { code: 'MS', label: 'Mississippi' },
  { code: 'MO', label: 'Missouri' },
  { code: 'MT', label: 'Montana' },
  { code: 'NE', label: 'Nebraska' },
  { code: 'NV', label: 'Nevada' },
  { code: 'NH', label: 'New Hampshire' },
  { code: 'NJ', label: 'New Jersey' },
  { code: 'NM', label: 'New Mexico' },
  { code: 'NY', label: 'New York' },
  { code: 'NC', label: 'North Carolina' },
  { code: 'ND', label: 'North Dakota' },
  { code: 'OH', label: 'Ohio' },
  { code: 'OK', label: 'Oklahoma' },
  { code: 'OR', label: 'Oregon' },
  { code: 'PA', label: 'Pennsylvania' },
  { code: 'PR', label: 'Puerto Rico' },
  { code: 'RI', label: 'Rhode Island' },
  { code: 'SC', label: 'South Carolina' },
  { code: 'SD', label: 'South Dakota' },
  { code: 'TN', label: 'Tennessee' },
  { code: 'TX', label: 'Texas' },
  { code: 'UT', label: 'Utah' },
  { code: 'VT', label: 'Vermont' },
  { code: 'VI', label: 'U.S. Virgin Islands' },
  { code: 'VA', label: 'Virginia' },
  { code: 'WA', label: 'Washington' },
  { code: 'WV', label: 'West Virginia' },
  { code: 'WI', label: 'Wisconsin' },
  { code: 'WY', label: 'Wyoming' },
  { code: 'MP', label: 'Northern Mariana Islands' },
  { code: 'PW', label: 'Palau' },
  { code: 'FM', label: 'Micronesia' },
  { code: 'MH', label: 'Marshall Islands' },
] as const

export const MARINE_AREA_OPTIONS = [
  { code: 'AM', label: 'Western North Atlantic south of North Carolina' },
  { code: 'AN', label: 'Western North Atlantic north of North Carolina' },
  { code: 'GM', label: 'Gulf of Mexico' },
  { code: 'LC', label: 'Lake St. Clair' },
  { code: 'LE', label: 'Lake Erie' },
  { code: 'LH', label: 'Lake Huron' },
  { code: 'LM', label: 'Lake Michigan' },
  { code: 'LO', label: 'Lake Ontario' },
  { code: 'LS', label: 'Lake Superior' },
  { code: 'PH', label: 'Central Pacific and Hawaiian waters' },
  { code: 'PK', label: 'North Pacific and Alaskan waters' },
  { code: 'PM', label: 'Western Pacific and Mariana Islands waters' },
  { code: 'PS', label: 'South Central Pacific and American Samoa waters' },
  { code: 'PZ', label: 'Eastern Pacific and U.S. West Coast' },
  { code: 'SL', label: 'St. Lawrence River' },
] as const

export type AlertAreaCode =
  | (typeof STATE_TERRITORY_AREA_OPTIONS)[number]['code']
  | (typeof MARINE_AREA_OPTIONS)[number]['code']

const alertAreaCodes = new Set<string>([
  ...STATE_TERRITORY_AREA_OPTIONS.map(({ code }) => code),
  ...MARINE_AREA_OPTIONS.map(({ code }) => code),
])

export function isAlertAreaCode(value: string): value is AlertAreaCode {
  return alertAreaCodes.has(value)
}
